# fly.toml app configuration file generated for flag-guesser-ui-long-shadow-5353 on 2025-09-27T04:57:56+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flag-guesser-ui-long-shadow-5353'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
